// try {
//     let x = undefined 
//     console.log(x[0]);
// } catch {
//     console.log("Error handling in catch");
// } finally {
//     console.log("Finally always gets executed");
// }

//-----------------------------------------------------------

// down code is without try-catch method

let x = undefined 
  console.log(x[0]);